// <auto-generated />
using System;
using Consultation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712184022_AddedMigration")]
    partial class AddedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consultation.Domain.ActionLog", b =>
                {
                    b.Property<int>("ActionLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionLogID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActionLogID");

                    b.HasIndex("UsersId");

                    b.ToTable("ActionLog");
                });

            modelBuilder.Entity("Consultation.Domain.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdminID");

                    b.HasIndex("UsersID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Consultation.Domain.Bulletin", b =>
                {
                    b.Property<int>("BulletinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BulletinID"));

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notify")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BulletinID");

                    b.ToTable("Bulletin");
                });

            modelBuilder.Entity("Consultation.Domain.ConsultationRequest", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultationID"));

                    b.Property<string>("Concern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSchedule")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisapprovedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndedTime")
                        .HasColumnType("time");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("NotificationNumber")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartedTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsultationID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("NotificationNumber");

                    b.HasIndex("StudentID");

                    b.ToTable("ConsultationRequest");
                });

            modelBuilder.Entity("Consultation.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "CASE",
                            Description = "College of Arts and Sciences Education"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "CBAE",
                            Description = "College of Business Administration Education"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "CEE",
                            Description = "College of Engineering Education"
                        });
                });

            modelBuilder.Entity("Consultation.Domain.EnrolledCourse", b =>
                {
                    b.Property<int>("EnrolledCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolledCourseID"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrolledCourseID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("SchoolYearID");

                    b.HasIndex("StudentID");

                    b.ToTable("EnrolledCourse");

                    b.HasData(
                        new
                        {
                            EnrolledCourseID = 1,
                            CourseCode = "CEE101",
                            CourseName = "Engineering Calculus 1",
                            FacultyID = 1,
                            SchoolYearID = 1,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 2,
                            CourseCode = "CEE102/L",
                            CourseName = "PHYSICS 1 FOR ENGINEERS (CALCULUS BASED)",
                            FacultyID = 2,
                            SchoolYearID = 1,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 3,
                            CourseCode = "CEE108",
                            CourseName = "Statics of Rigid Bodies",
                            FacultyID = 2,
                            SchoolYearID = 1,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 4,
                            CourseCode = "CEE108",
                            CourseName = "Statics of Rigid Bodies",
                            FacultyID = 2,
                            SchoolYearID = 1,
                            StudentID = 2
                        },
                        new
                        {
                            EnrolledCourseID = 5,
                            CourseCode = "CEE103",
                            CourseName = "Engineering Calculus 2",
                            FacultyID = 2,
                            SchoolYearID = 2,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 6,
                            CourseCode = "CEE101",
                            CourseName = "Thermodyanmics 2",
                            FacultyID = 1,
                            SchoolYearID = 2,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 7,
                            CourseCode = "CPE221/L",
                            CourseName = "Data Structure and Algorithms",
                            FacultyID = 2,
                            SchoolYearID = 2,
                            StudentID = 1
                        },
                        new
                        {
                            EnrolledCourseID = 8,
                            CourseCode = "CEE104",
                            CourseName = "Differential Equation",
                            FacultyID = 2,
                            SchoolYearID = 3,
                            StudentID = 1
                        });
                });

            modelBuilder.Entity("Consultation.Domain.Faculty", b =>
                {
                    b.Property<int>("FacultyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyID"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyUMID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYearID")
                        .HasColumnType("int");

                    b.Property<string>("UsersID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FacultyID");

                    b.HasIndex("SchoolYearID");

                    b.HasIndex("UsersID");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            FacultyID = 1,
                            FacultyName = "Rey Mateo",
                            FacultyUMID = "321033",
                            SchoolYearID = 1,
                            UsersID = "53D8F920-EBEC-4DF3-8C53-21F6D123F0D9"
                        },
                        new
                        {
                            FacultyID = 2,
                            FacultyName = "Jeanelle Labsan",
                            FacultyUMID = "797132",
                            SchoolYearID = 2,
                            UsersID = "78B4AF2A-672F-43C5-B819-5F0B407B7187"
                        });
                });

            modelBuilder.Entity("Consultation.Domain.FacultySchedule", b =>
                {
                    b.Property<int>("FacultyScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyScheduleID"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("FacultyScheduleID");

                    b.HasIndex("FacultyID");

                    b.ToTable("FacultySchedule");
                });

            modelBuilder.Entity("Consultation.Domain.Notification", b =>
                {
                    b.Property<int>("NotificationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationNumber"));

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationNumber");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Consultation.Domain.Program", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Program");

                    b.HasData(
                        new
                        {
                            ProgramID = 1,
                            DepartmentID = 3,
                            Description = "Mechanical Engineering",
                            ProgramName = "ME"
                        },
                        new
                        {
                            ProgramID = 2,
                            DepartmentID = 3,
                            Description = "Civil Engineering",
                            ProgramName = "CE"
                        },
                        new
                        {
                            ProgramID = 3,
                            DepartmentID = 3,
                            Description = "Computer Engineering",
                            ProgramName = "CPE"
                        },
                        new
                        {
                            ProgramID = 4,
                            DepartmentID = 3,
                            Description = "Electrical Engineering",
                            ProgramName = "EE"
                        },
                        new
                        {
                            ProgramID = 5,
                            DepartmentID = 3,
                            Description = "Electronics Engineering",
                            ProgramName = "ECE"
                        });
                });

            modelBuilder.Entity("Consultation.Domain.SchoolYear", b =>
                {
                    b.Property<int>("SchoolYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolYearID"));

                    b.Property<int>("SchoolYearStatus")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Year1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolYearID");

                    b.ToTable("SchoolYear");

                    b.HasData(
                        new
                        {
                            SchoolYearID = 1,
                            SchoolYearStatus = 1,
                            Semester = 1,
                            Year1 = "2024",
                            Year2 = "2025"
                        },
                        new
                        {
                            SchoolYearID = 2,
                            SchoolYearStatus = 1,
                            Semester = 2,
                            Year1 = "2024",
                            Year2 = "2025"
                        },
                        new
                        {
                            SchoolYearID = 3,
                            SchoolYearStatus = 1,
                            Semester = 3,
                            Year1 = "2024",
                            Year2 = "2025"
                        });
                });

            modelBuilder.Entity("Consultation.Domain.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearID")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentUMID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("SchoolYearID");

                    b.HasIndex("UsersID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Email = "CedricSetimo.550200@umindanao.edu.ph",
                            ProgramID = 3,
                            SchoolYearID = 1,
                            StudentName = "Cedric Setimo",
                            StudentUMID = "550200",
                            UsersID = "273F528F-5330-411F-9C6B-01543D6249C3"
                        },
                        new
                        {
                            StudentID = 2,
                            Email = "EllaineMusni.550200@umindanao.edu.ph",
                            ProgramID = 3,
                            SchoolYearID = 1,
                            StudentName = "Ellaine Musni",
                            StudentUMID = "547343",
                            UsersID = "D0B26692-E380-4374-985F-239B56D06C20"
                        });
                });

            modelBuilder.Entity("Consultation.Domain.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UMID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "273F528F-5330-411F-9C6B-01543D6249C3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "CedricSetimo.550200@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CEDRICSETIMO.550200@UMINDANAO.EDU.PH",
                            NormalizedUserName = "CEDRIC SETIMO",
                            PasswordHash = "AQAAAAIAAYagAAAAEBVscVrnbETQEzEug+ZHSyKb718dAwNjpvnbFbbpXDOOLF1KUM68r8Z76i10ipq5Gw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "550200",
                            UserName = "Cedric Setimo",
                            UserType = 1
                        },
                        new
                        {
                            Id = "53D8F920-EBEC-4DF3-8C53-21F6D123F0D9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "ReyMateo.550200@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "REYMATEO.550200@UMINDANAO.EDU.PH",
                            NormalizedUserName = "REY MATEO",
                            PasswordHash = "AQAAAAIAAYagAAAAED+J9yAjrDs7TP47SJaeAPCiEDVUSnkEPYwEO1uHQP0jkwajt43Ba1bQ2/mJFxIGhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "321033",
                            UserName = "Rey Mateo",
                            UserType = 2
                        },
                        new
                        {
                            Id = "6B187E9D-FD71-4F1D-AFDF-EA1D91E818EF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "RaineIsid.550200@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RAINEISID.550200@UMINDANAO.EDU.PH",
                            NormalizedUserName = "RAINE ISID",
                            PasswordHash = "AQAAAAIAAYagAAAAEDzQaRNixrNE53loy/f8gbI+r7eWANC5l8yvuaWeuWN1A/2XNhGfnKnlNCLzQ+MzPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "444533",
                            UserName = "Raine Isid",
                            UserType = 3
                        },
                        new
                        {
                            Id = "D0B26692-E380-4374-985F-239B56D06C20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "EllaineMusni.550200@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELLAINEMUSNI.550200@UMINDANAO.EDU.PH",
                            NormalizedUserName = "ELLAINE MUSNI",
                            PasswordHash = "AQAAAAIAAYagAAAAELPV1r4YAoj278KzKRrZVDE/KZXOViuujxy7+AsY8xujjpwUaPfHIsf8B9l+ll7sIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "547343",
                            UserName = "Ellaine Musni",
                            UserType = 1
                        },
                        new
                        {
                            Id = "1226920F-9508-44B3-845A-ABABBBCBCF5D",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "ReggieSoylon.6850@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "REGGIESOYLON.6850@UMINDANAO.EDU.PH",
                            NormalizedUserName = "REGGIE SOYLON",
                            PasswordHash = "AQAAAAIAAYagAAAAEKyLTLyPrEx4eSLbJxgVMJxkx45jrtsJJzHsZheEWoug4w/UTCIdYKMdV/vCEkYfBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "685043",
                            UserName = "Reggie Soylon",
                            UserType = 1
                        },
                        new
                        {
                            Id = "0A52E15B-95E6-40FE-9110-9A44817BFF39",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "CheleyBalsomo.8998@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHELEYBALSOMO.8998@UMINDANAO.EDU.PH",
                            NormalizedUserName = "CHELEY BALSOMO",
                            PasswordHash = "AQAAAAIAAYagAAAAEJooLhPBWMuBCRYqIc4BewtJAkEbNLeqBgiu7cV4NL6JcDQJ9Iwc1Rm+kkgFWjotow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "899812",
                            UserName = "Cheley Balsomo",
                            UserType = 1
                        },
                        new
                        {
                            Id = "78B4AF2A-672F-43C5-B819-5F0B407B7187",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "JeanelleLabsan.7971@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JEANELLELABSAN.7971@UMINDANAO.EDU.PH",
                            NormalizedUserName = "JEANELLE LABSAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdN6078qF3SAUq/yDl4i7P3/3G7IL5ztA6cVNC1oBYEmctgklWBAnwuyDXXeJvmbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "797132",
                            UserName = "Jeanelle Labsan",
                            UserType = 2
                        },
                        new
                        {
                            Id = "59CF8531-68E4-466B-BAEC-45305FE16A14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d3ef0d9-b045-4b8f-a18f-15f2cbfa219b",
                            Email = "ChristopherDestajo.9241@umindanao.edu.ph",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHRISTOPHERDESTAJO.9241@UMINDANAO.EDU.PH",
                            NormalizedUserName = "CHRISTOPHER DESTAJO",
                            PasswordHash = "AQAAAAIAAYagAAAAEH3ZrT8Pcw0i7AgrbZ+Vvb3J9nABysUI+f5KJ5N7KuZhDLKIjnLv6M52UyG31Xwhog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a54c967-0b1f-4c38-bda7-5f94e4c1a3f4",
                            TwoFactorEnabled = false,
                            UMID = "924132",
                            UserName = "Christopher Destajo",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Consultation.Domain.ActionLog", b =>
                {
                    b.HasOne("Consultation.Domain.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Consultation.Domain.Admin", b =>
                {
                    b.HasOne("Consultation.Domain.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Consultation.Domain.ConsultationRequest", b =>
                {
                    b.HasOne("Consultation.Domain.Faculty", "Faculty")
                        .WithMany("ConsultationRequests")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Student", "Student")
                        .WithMany("ConsultationRequests")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Notification");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Consultation.Domain.EnrolledCourse", b =>
                {
                    b.HasOne("Consultation.Domain.Faculty", "Faculty")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.SchoolYear", "SchoolYear")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("SchoolYearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Student", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Consultation.Domain.Faculty", b =>
                {
                    b.HasOne("Consultation.Domain.SchoolYear", "SchoolYear")
                        .WithMany("Faculties")
                        .HasForeignKey("SchoolYearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Consultation.Domain.FacultySchedule", b =>
                {
                    b.HasOne("Consultation.Domain.Faculty", "Faculty")
                        .WithMany("FacultySchedules")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Consultation.Domain.Program", b =>
                {
                    b.HasOne("Consultation.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Consultation.Domain.Student", b =>
                {
                    b.HasOne("Consultation.Domain.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.SchoolYear", "SchoolYear")
                        .WithMany("Students")
                        .HasForeignKey("SchoolYearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("SchoolYear");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Consultation.Domain.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Consultation.Domain.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consultation.Domain.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Consultation.Domain.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consultation.Domain.Faculty", b =>
                {
                    b.Navigation("ConsultationRequests");

                    b.Navigation("EnrolledCourses");

                    b.Navigation("FacultySchedules");
                });

            modelBuilder.Entity("Consultation.Domain.SchoolYear", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Faculties");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Consultation.Domain.Student", b =>
                {
                    b.Navigation("ConsultationRequests");

                    b.Navigation("EnrolledCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
